export const userId = state => state.loginStatus.userId
export const isLogin = state => state.loginStatus.isLogin
export const userInfo = state => state.userInfo
export const accounts = state => state.accounts
export const allMessage = state => state.message.allMessage
export const hasGetFriendList = state => state.friend.hasGetFriendList
export const friendList = state => state.friend.friendList
export const friendStatus = state => state.friend.friendStatus
export const fenzu = state => state.friend.fenzu
export const hasGetNewFriends = state => state.friend.hasGetNewFriends
export const newFriends = state => state.friend.newFriends
export const isShowSideBar = state => state.sidebar.isShowSideBar
export const isShowMask = state => state.sidebar.isShowMask
export const scrollPosition = state => state.scroll.position
export const tabIndex = state => state.friend.tabIndex