export const SET_LOGIN = 'SET_LOGIN'
export const SHOW_SIDEBAR = 'SHOW_SIDEBAR'
export const SET_INIT = 'SET_INIT'
export const SHOW_WARN = 'SHOW_WARN'
export const GET_ALL_MESSAGE = 'GET_ALL_MESSAGE'
export const GET_FRIEND_LIST = 'GET_FRIEND_LIST'